DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (  
    no          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "PK",
    id          VARCHAR(100) NOT NULL COMMENT "UK",
    username    VARCHAR(100) NOT NULL COMMENT "아이디",
    password    VARCHAR(100) NOT NULL COMMENT "비밀번호",
    name        VARCHAR(100) NULL COMMENT "이름",
    email       VARCHAR(100) NULL COMMENT "이메일",
    created_at  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT "등록일자",
    updated_at  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT "등록일자",
    enabled     BOOLEAN NULL DEFAULT TRUE COMMENT "활성화여부"
) COMMENT '회원';

CREATE TABLE `user_auth` (
    no          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "PK",
    username    VARCHAR(100) NOT NULL COMMENT "아이디",
    auth        VARCHAR(100) NOT NULL COMMENT "권한"
) COMMENT "회원권한";